import { createApi, fetchBaseQuery } from "@reduxjs/toolkit/query/react";
import { GetKpisResponse, GetProductsResponse } from "./types";

export const api = createApi({
  reducerPath: "main",
  // used for invalidation and caechcing
  tagTypes: ["Kpis", "Products"],
  baseQuery: fetchBaseQuery({ baseUrl: import.meta.env.VITE_BASE_URL }),
  endpoints: (builder) => ({
    getKpis: builder.query<Array<GetKpisResponse>, void>({
      query: () => `/kpi/kpis`,
      providesTags: ["Kpis"],
    }),

    getProducts: builder.query<Array<GetProductsResponse>, void>({
      query: () => "/product/products",
      providesTags: ["Products"],
    }),
  }),
});

/* exporting autogenerated hooks for using in the components */
/* GET /product/products  */
export const { useGetKpisQuery, useGetProductsQuery } = api;
